api/urls.py
from django.urls import path
from .views import (
    index,
    download_graphed_data
)


app_name = 'api'


urlpatterns = [
    path('', index, name='api'),
    path('download_graphed_data', download_graphed_data, name='download_graphed_data'),
   
]

configuration_sddp/urls.py
from django.urls import path
from .views import (
    search,
    fuel_price_option,
    growing_rate,
    project,
    graph_year,
    additional_capacity,
    meta_matrix,
    max_new_capacity,
    lcoe_energy_cost,
    demand,
    plant_type,
    fuel,
    existing_plants,
    future_plants
)


app_name = 'configuration_sddp'


urlpatterns = [
    # path('project_old', old_project.ProjectListView.as_view(), name='old_project_list'),
    # path('project_old/create', old_project.ProjectCreateView.as_view(), name='old_project_create'),
    # path('interaction_type/<int:pk>/change', interaction_type.InteractionTypeChangeView.as_view(), name='interaction_type_change'),
    # path('interaction_type/<int:pk>/delete', interaction_type.InteractionTypeDeleteView.as_view(), name='interaction_type_delete')

    path('search', search.SearchTemplateView.as_view(), name='search_view'),

    path('fuel_price_option', fuel_price_option.FuelPriceOptionListView.as_view(), name='fuel_price_option_list'),
    path('fuel_price_option/create', fuel_price_option.FuelPriceOptionCreateView.as_view(), name='fuel_price_option_create'),
    path('fuel_price_option/<int:pk>/change', fuel_price_option.FuelPriceOptionUpdateView.as_view(), name='fuel_price_option_change'),
    path('fuel_price_option/<int:pk>/delete', fuel_price_option.FuelPriceOptionDeleteView.as_view(), name='fuel_price_option_delete'),

    path('growing_rate', growing_rate.GrowingRateListView.as_view(), name='growing_rate_list'),
    path('growing_rate/create', growing_rate.GrowingRateCreateView.as_view(), name='growing_rate_create'),
    path('growing_rate/<int:pk>/change', growing_rate.GrowingRateUpdateView.as_view(), name='growing_rate_change'),
    path('growing_rate/<int:pk>/delete', growing_rate.GrowingRateDeleteView.as_view(), name='growing_rate_delete'),

    path('project', project.ProjectListView.as_view(), name='project_list'),
    path('project/create', project.ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/change', project.ProjectUpdateView.as_view(), name='project_change'),
    path('project/<int:pk>/delete', project.ProjectDeleteView.as_view(), name='project_delete'),

    path('graph_year', graph_year.GraphYearListView.as_view(), name='graph_year_list'),
    path('graph_year/create', graph_year.GraphYearCreateView.as_view(), name='graph_year_create'),
    path('graph_year/<int:pk>/change', graph_year.GraphYearUpdateView.as_view(), name='graph_year_change'),
    path('graph_year/<int:pk>/delete', graph_year.GraphYearDeleteView.as_view(), name='graph_year_delete'),

    path('additional_capacity', additional_capacity.AdditionalCapacityListView.as_view(), name='additional_capacity_list'),
    path('additional_capacity/create', additional_capacity.AdditionalCapacityCreateView.as_view(), name='additional_capacity_create'),
    path('additional_capacity/<int:pk>/change', additional_capacity.AdditionalCapacityUpdateView.as_view(), name='additional_capacity_change'),
    path('additional_capacity/<int:pk>/delete', additional_capacity.AdditionalCapacityDeleteView.as_view(), name='additional_capacity_delete'),

    path('meta_matrix', meta_matrix.MetaMatrixListView.as_view(), name='meta_matrix_list'),
    path('meta_matrix/create', meta_matrix.MetaMatrixCreateView.as_view(), name='meta_matrix_create'),
    path('meta_matrix/<int:pk>/change', meta_matrix.MetaMatrixUpdateView.as_view(), name='meta_matrix_change'),
    path('meta_matrix/<int:pk>/delete', meta_matrix.MetaMatrixDeleteView.as_view(), name='meta_matrix_delete'),

    path('max_new_capacity', max_new_capacity.MaxNewCapacityListView.as_view(), name='max_new_capacity_list'),
    path('max_new_capacity/create', max_new_capacity.MaxNewCapacityCreateView.as_view(), name='max_new_capacity_create'),
    path('max_new_capacity/<int:pk>/change', max_new_capacity.MaxNewCapacityUpdateView.as_view(), name='max_new_capacity_change'),
    path('max_new_capacity/<int:pk>/delete', max_new_capacity.MaxNewCapacityDeleteView.as_view(), name='max_new_capacity_delete'),

    path('lcoe_energy_cost', lcoe_energy_cost.LcoeEnergyCostListView.as_view(), name='lcoe_energy_cost_list'),
    path('lcoe_energy_cost/create', lcoe_energy_cost.LcoeEnergyCostCreateView.as_view(), name='lcoe_energy_cost_create'),
    path('lcoe_energy_cost/<int:pk>/change', lcoe_energy_cost.LcoeEnergyCostUpdateView.as_view(), name='lcoe_energy_cost_change'),
    path('lcoe_energy_cost/<int:pk>/delete', lcoe_energy_cost.LcoeEnergyCostDeleteView.as_view(), name='lcoe_energy_cost_delete'),

    path('demand', demand.DemandListView.as_view(), name='demand_list'),
    path('demand/create', demand.DemandCreateView.as_view(), name='demand_create'),
    path('demand/<int:pk>/change', demand.DemandUpdateView.as_view(), name='demand_change'),
    path('demand/<int:pk>/delete', demand.DemandDeleteView.as_view(), name='demand_delete'),

    path('plant_type', plant_type.PlantTypeListView.as_view(), name='plant_type_list'),
    path('plant_type/create', plant_type.PlantTypeCreateView.as_view(), name='plant_type_create'),
    path('plant_type/<int:pk>/change', plant_type.PlantTypeUpdateView.as_view(), name='plant_type_change'),
    path('plant_type/<int:pk>/delete', plant_type.PlantTypeDeleteView.as_view(), name='plant_type_delete'),

    path('fuel', fuel.FuelListView.as_view(), name='fuel_list'),
    path('fuel/create', fuel.FuelCreateView.as_view(), name='fuel_create'),
    path('fuel/<int:pk>/change', fuel.FuelUpdateView.as_view(), name='fuel_change'),
    path('fuel/<int:pk>/delete', fuel.FuelDeleteView.as_view(), name='fuel_delete'),

    path('existing_plants', existing_plants.ExistingPlantsListView.as_view(), name='existing_plants_list'),
    path('existing_plants/create', existing_plants.ExistingPlantsCreateView.as_view(), name='existing_plants_create'),
    path('existing_plants/<int:pk>/change', existing_plants.ExistingPlantsUpdateView.as_view(), name='existing_plants_change'),
    path('existing_plants/<int:pk>/delete', existing_plants.ExistingPlantsDeleteView.as_view(), name='existing_plants_delete'),

    path('future_plants', future_plants.FuturePlantsListView.as_view(), name='future_plants_list'),
    path('future_plants/create', future_plants.FuturePlantsCreateView.as_view(), name='future_plants_create'),
    path('future_plants/<int:pk>/change', future_plants.FuturePlantsUpdateView.as_view(), name='future_plants_change'),
    path('future_plants/<int:pk>/delete', future_plants.FuturePlantsDeleteView.as_view(), name='future_plants_delete'),
]

datcore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('users.urls', namespace='users')),
    path('imports/', include('imports.urls', namespace='imports')),
    path('api/', include('api.urls', namespace='api')),
    path('lessons/', include('lessons.urls', namespace='lessons')),
    path('sddp/', include('sddp.urls', namespace='sddp')),
    path('budgeted_hours/', include('budgeted_hours.urls', namespace='budgeted_hours')),
    path('reported_hours/', include('reported_hours.urls', namespace='reported_hours')),
    path('record_business_interactions/', include('record_business_interactions.urls', namespace='record_business_interactions')),
    path('vacations/', include('vacations.urls', namespace = 'vacations')),
    path('configuration_sddp/', include('configuration_sddp.urls', namespace = 'configuration_sddp')),
    path('documents/', include('documents.urls', namespace='documents')),
    path('markers/', include('markers.urls', namespace='markers')),
]
 

configuration_sddp/forms/additional_capacity_form.py
from django import forms
from configuration_sddp.models import AdditionalCapacity


class AdditionalCapacityForm(forms.ModelForm):

    class Meta:
        model = AdditionalCapacity
        fields = '__all__'

configuration_sddp/forms/demand_form.py
from django import forms
from configuration_sddp.models import Demand


class DemandForm(forms.ModelForm):

    class Meta:
        model = Demand
        fields = '__all__'

configuration_sddp/forms/fuel_form.py
from django import forms
from configuration_sddp.models import Fuel


class FuelForm(forms.ModelForm):

    class Meta:
        model = Fuel
        fields = '__all__'

configuration_sddp/views/additional_capacity.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from configuration_sddp.models import AdditionalCapacity
from configuration_sddp.forms.additional_capacity_form import AdditionalCapacityForm


class AdditionalCapacityListView(PermissionRequiredMixin, ListView):

    model = AdditionalCapacity
    template_name = 'additional_capacity/list.html'
    context_object_name = 'additional_capacity'
    permission_required = ''


class AdditionalCapacityCreateView(PermissionRequiredMixin, CreateView):

    model = AdditionalCapacity
    form_class = AdditionalCapacityForm
    template_name = 'additional_capacity/create.html'
    success_url = reverse_lazy('configuration_sddp:additional_capacity_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro creado con éxito')
        return super().form_valid(form)


class AdditionalCapacityUpdateView(PermissionRequiredMixin, UpdateView):

    model = AdditionalCapacity
    form_class = AdditionalCapacityForm
    template_name = 'additional_capacity/change.html'
    success_url = reverse_lazy('configuration_sddp:additional_capacity_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro actualizado con éxito')
        return super().form_valid(form)


class AdditionalCapacityDeleteView(PermissionRequiredMixin, DeleteView):

    model = AdditionalCapacity
    template_name = 'additional_capacity/delete.html'
    success_url = reverse_lazy('configuration_sddp:additional_capacity_list')
    context_object_name = 'additional_capacity'
    permission_required = ''

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Registro eliminado con éxito')
        return super().delete(*args, **kwargs)

configuration_sddp/views/demand.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from configuration_sddp.models import Demand
from configuration_sddp.forms.demand_form import DemandForm


class DemandListView(PermissionRequiredMixin, ListView):

    model = Demand
    template_name = 'demand/list.html'
    context_object_name = 'demand'
    permission_required = ''


class DemandCreateView(PermissionRequiredMixin, CreateView):

    model = Demand
    form_class = DemandForm
    template_name = 'demand/create.html'
    success_url = reverse_lazy('configuration_sddp:demand_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro creado con éxito')
        return super().form_valid(form)


class DemandUpdateView(PermissionRequiredMixin, UpdateView):

    model = Demand
    form_class = DemandForm
    template_name = 'demand/change.html'
    success_url = reverse_lazy('configuration_sddp:demand_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro actualizado con éxito')
        return super().form_valid(form)


class DemandDeleteView(PermissionRequiredMixin, DeleteView):

    model = Demand
    template_name = 'demand/delete.html'
    success_url = reverse_lazy('configuration_sddp:demand_list')
    context_object_name = 'demand'
    permission_required = ''

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Registro eliminado con éxito')
        return super().delete(*args, **kwargs)

configuration_sddp/views/existing_plants.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from configuration_sddp.models import ExistingPlants
from configuration_sddp.forms.existing_plants_form import ExistingPlantsForm


class ExistingPlantsListView(PermissionRequiredMixin, ListView):

    model = ExistingPlants
    template_name = 'existing_plants/list.html'
    context_object_name = 'existing_plants'
    permission_required = ''


class ExistingPlantsCreateView(PermissionRequiredMixin, CreateView):

    model = ExistingPlants
    form_class = ExistingPlantsForm
    template_name = 'existing_plants/create.html'
    success_url = reverse_lazy('configuration_sddp:existing_plants_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro creado con éxito')
        return super().form_valid(form)


class ExistingPlantsUpdateView(PermissionRequiredMixin, UpdateView):

    model = ExistingPlants
    form_class = ExistingPlantsForm
    template_name = 'existing_plants/change.html'
    success_url = reverse_lazy('configuration_sddp:existing_plants_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro actualizado con éxito')
        return super().form_valid(form)


class ExistingPlantsDeleteView(PermissionRequiredMixin, DeleteView):

    model = ExistingPlants
    template_name = 'existing_plants/delete.html'
    success_url = reverse_lazy('configuration_sddp:existing_plants_list')
    context_object_name = 'existing_plants'
    permission_required = ''

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Registro eliminado con éxito')
        return super().delete(*args, **kwargs)

configuration_sddp/views/fuel.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from configuration_sddp.models import Fuel
from configuration_sddp.forms.fuel_form import FuelForm


class FuelListView(PermissionRequiredMixin, ListView):

    model = Fuel
    template_name = 'fuel/list.html'
    context_object_name = 'fuel'
    permission_required = ''


class FuelCreateView(PermissionRequiredMixin, CreateView):

    model = Fuel
    form_class = FuelForm
    template_name = 'fuel/create.html'
    success_url = reverse_lazy('configuration_sddp:fuel_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro creado con éxito')
        return super().form_valid(form)


class FuelUpdateView(PermissionRequiredMixin, UpdateView):

    model = Fuel
    form_class = FuelForm
    template_name = 'fuel/change.html'
    success_url = reverse_lazy('configuration_sddp:fuel_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro actualizado con éxito')
        return super().form_valid(form)


class FuelDeleteView(PermissionRequiredMixin, DeleteView):

    model = Fuel
    template_name = 'fuel/delete.html'
    success_url = reverse_lazy('configuration_sddp:fuel_list')
    context_object_name = 'fuel'
    permission_required = ''

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Registro eliminado con éxito')
        return super().delete(*args, **kwargs)

configuration_sddp/views/fuel_price_option.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from configuration_sddp.models import FuelPriceOption
from configuration_sddp.forms.fuel_price_option_form import FuelPriceOptionForm


class FuelPriceOptionListView(PermissionRequiredMixin, ListView):

    model = FuelPriceOption
    template_name = 'fuel_price_option/list.html'
    context_object_name = 'fuelpriceoption'
    permission_required = ''


class FuelPriceOptionCreateView(PermissionRequiredMixin, CreateView):

    model = FuelPriceOption
    form_class = FuelPriceOptionForm
    template_name = 'fuel_price_option/create.html'
    success_url = reverse_lazy('configuration_sddp:fuel_price_option_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro creado con éxito')
        return super().form_valid(form)


class FuelPriceOptionUpdateView(PermissionRequiredMixin, UpdateView):

    model = FuelPriceOption
    form_class = FuelPriceOptionForm
    template_name = 'fuel_price_option/change.html'
    success_url = reverse_lazy('configuration_sddp:fuel_price_option_list')
    permission_required = ''

    def form_valid(self, form):
        messages.success(self.request, 'Registro actualizado con éxito')
        return super().form_valid(form)


class FuelPriceOptionDeleteView(PermissionRequiredMixin, DeleteView):

    model = FuelPriceOption
    template_name = 'fuel_price_option/delete.html'
    success_url = reverse_lazy('configuration_sddp:fuel_price_option_list')
    context_object_name = 'fuelpriceoption'
    permission_required = ''

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Registro eliminado con éxito')
        return super().delete(*args, **kwargs)

configuration_sddp/templates/growing_rate/change.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Tasa de crecimiento</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Editar</h4>
                <p class="card-title-desc">Actualice la información</p>

                <form method='POST'>

                    {% csrf_token %}

                    {{ form|crispy }}

                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-primary float-right">Guardar</button>
                            <a href="{% url 'configuration_sddp:growing_rate_list' %}" class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

configuration_sddp/templates/growing_rate/create.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Tasa de crecimiento</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Crear</h4>
                <p class="card-title-desc">Ingrese la información que desea registrar</p>

                <form method="POST">

                    {% csrf_token %}
                    {{ form|crispy }}

                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-primary float-right">Guardar</button>
                            <a href="{% url 'configuration_sddp:growing_rate_list' %}"  class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

configuration_sddp/templates/growing_rate/delete.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Tasa de crecimiento</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Eliminar</h4>

                <form method='POST'>

                    {% csrf_token %}

                    <p>Realmente desea eliminar este elemento?</p>
                    <p>
                        Nombre: <b>{{ growingrate }}</b>
                    </p>

                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-danger float-right">Eliminar</button>
                            <a href="{% url 'configuration_sddp:growing_rate_list' %}" class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

configuration_sddp/templates/growing_rate/list.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Tasa de crecimiento</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">
                    Lista
                    <a class='float-right btn btn-success' href="{% url 'configuration_sddp:growing_rate_create' %}">Crear</a>
                </h4>

                <div class="table-responsive">
                    <table class="table table-centered table-vertical table-nowrap mb-1">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th class="text-right">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in growingrate %}
                                <tr>
                                    <td>{{ item.name }}</td>
                                    <td class="text-right">
                                        <a href="{% url 'configuration_sddp:growing_rate_change' item.pk  %}" class="btn btn-warning btn-sm">Editar</a>
                                        <a href="{% url 'configuration_sddp:growing_rate_delete' item.pk  %}" class="btn btn-danger btn-sm">Eliminar</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}