api/urls.py
from django.urls import path
from .views import (
    index,
    download_graphed_data
)


app_name = 'api'


urlpatterns = [
    path('', index, name='api'),
    path('download_graphed_data', download_graphed_data, name='download_graphed_data'),
   
]

datcore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('users.urls', namespace='users')),
    path('imports/', include('imports.urls', namespace='imports')),
    path('api/', include('api.urls', namespace='api')),
    path('lessons/', include('lessons.urls', namespace='lessons')),
    path('sddp/', include('sddp.urls', namespace='sddp')),
    path('budgeted_hours/', include('budgeted_hours.urls', namespace='budgeted_hours')),
    path('reported_hours/', include('reported_hours.urls', namespace='reported_hours')),
    path('record_business_interactions/', include('record_business_interactions.urls', namespace='record_business_interactions')),
    path('vacations/', include('vacations.urls', namespace = 'vacations')),
    path('configuration_sddp/', include('configuration_sddp.urls', namespace = 'configuration_sddp')),
    path('documents/', include('documents.urls', namespace='documents')),
    path('markers/', include('markers.urls', namespace='markers')),
]
 

lessons/urls.py
from django.urls import path
from .views import (
    electrical_studies,
    consultancies,
    protection_coordination_studies,
    connection_studies,
    market_studies,
    reports
)


app_name = 'lessons'


urlpatterns = [
    path('electrical-studies', electrical_studies.ElectricalStudiesListView.as_view(), name='electrical_studies_list'),
    path('electrical-studies/create', electrical_studies.ElectricalStudiesCreateView.as_view(), name='electrical_studies_create'),
    path('electrical-studies/<int:pk>/view', electrical_studies.ElectricalStudiesDetailView.as_view(), name='electrical_studies_detail'),
    path('electrical-studies/<int:pk>/change', electrical_studies.ElectricalStudiesUpdateView.as_view(), name='electrical_studies_change'),
    path('electrical-studies/<int:pk>/delete', electrical_studies.ElectricalStudiesDeleteView.as_view(), name='electrical_studies_delete'),

    path('consultancies', consultancies.ConsultanciesListView.as_view(), name='consultancies_list'),
    path('consultancies/create', consultancies.ConsultanciesCreateView.as_view(), name='consultancies_create'),
    path('consultancies/<int:pk>/view', consultancies.ConsultanciesDetailView.as_view(), name='consultancies_detail'),
    path('consultancies/<int:pk>/change', consultancies.ConsultanciesUpdateView.as_view(), name='consultancies_change'),
    path('consultancies/<int:pk>/delete', consultancies.ConsultanciesDeleteView.as_view(), name='consultancies_delete'),

    path('protection-coordination-studies', protection_coordination_studies.ProtectionCoordinationStudiesListView.as_view(), name='protection_coordination_studies_list'),
    path('protection-coordination-studies/create', protection_coordination_studies.ProtectionCoordinationStudiesCreateView.as_view(), name='protection_coordination_studies_create'),
    path('protection-coordination-studies/<int:pk>/view', protection_coordination_studies.ProtectionCoordinationStudiesDetailView.as_view(), name='protection_coordination_studies_detail'),
    path('protection-coordination-studies/<int:pk>/change', protection_coordination_studies.ProtectionCoordinationStudiesUpdateView.as_view(), name='protection_coordination_studies_change'),
    path('protection-coordination-studies/<int:pk>/delete', protection_coordination_studies.ProtectionCoordinationStudiesDeleteView.as_view(), name='protection_coordination_studies_delete'),

    path('connection-studies', connection_studies.ConnectionStudiesListView.as_view(), name='connection_studies_list'),
    path('connection-studies/create', connection_studies.ConnectionStudiesCreateView.as_view(), name='connection_studies_create'),
    path('connection-studies/<int:pk>/view', connection_studies.ConnectionStudiesDetailView.as_view(), name='connection_studies_detail'),
    path('connection-studies/<int:pk>/change', connection_studies.ConnectionStudiesChangeView.as_view(), name='connection_studies_change'),
    path('connection-studies/<int:pk>/delete', connection_studies.ConnectionStudiesDeleteView.as_view(), name='connection_studies_delete'),

    path('connection-studies/operatos', connection_studies.getOperators, name='operatos'),
    path('connection-studies/areas', connection_studies.getAreas, name='areas'),

    path('market-studies', market_studies.MarketStudiesListView.as_view(), name='market_studies_list'),
    path('market-studies/create', market_studies.MarketStudiesCreateView.as_view(), name='market_studies_create'),
    path('market-studies/<int:pk>/view', market_studies.MarketStudiesDetailView.as_view(), name='market_studies_detail'),
    path('market-studies/<int:pk>/change', market_studies.MarketStudiesChangeView.as_view(), name='market_studies_change'),
    path('market-studies/<int:pk>/delete', market_studies.MarketStudiesDeleteView.as_view(), name='market_studies_delete'),

    path('reports', reports.ReportsTemplateView.as_view(), name='reports_lessons'),

    # path('commercial', commercial.CommercialListView.as_view(), name='commercial_list'),
    # path('commercial/create', commercial.CommercialCreateView.as_view(), name='commercial_create'),
    # path('commercial/<int:pk>/view', commercial.CommercialDetailView.as_view(), name='commercial_detail'),
    # path('commercial/<int:pk>/change', commercial.CommercialChangeView.as_view(), name='commercial_change'),
    # path('commercial/<int:pk>/delete', commercial.CommercialDeleteView.as_view(), name='commercial_delete'),

    # path('related_area', related_areas.RelatedAreaListView.as_view(), name='related_area_list'),
    # path('related_area/create', related_areas.RelatedAreaCreateView.as_view(), name='related_area_create'),
    # path('related_area/<int:pk>/change', related_areas.RelatedAreaChangeView.as_view(), name='related_area_change'),
    # path('related_area/<int:pk>/delete', related_areas.RelatedAreaDeleteView.as_view(), name='related_area_delete'),

    # path('connection-studies/<int:pk>/view', connection_studies.ConnectionStudiesDetailView.as_view(), name='connection_studies_detail'),

    # path('market-studies/<int:pk>/view', market_studies.MarketStudiesDetailView.as_view(), name='market_studies_detail'),

    # path('market-studies/files/<int:pk>', market_studies_files.MarketStudiesFilesChangeView.as_view(), name='market_studies_list_files'),

    # path('market-studies/information-types', market_studies.get_information_types, name='information_types'),
    # path('market-studies/characteristics', market_studies.get_characteristics, name='characteristics'),

]

lessons/models.py
from django.db import models
from django.contrib.auth.models import User
from budgeted_hours.models import Client, BudgetedHours


# Create your models here.
LESSON_TYPE = [
    (1, 'Técnica'),
    (2, 'Gestión del proyecto'),
    (3, 'General')
]


class ElectricalStudies(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateField(blank=False, null=False)
    budgeted_hours = models.ForeignKey(BudgetedHours, on_delete=models.CASCADE, blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    lesson_type = models.IntegerField(choices=LESSON_TYPE, blank=False, null=False)
    action_plan = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='static/static/lessons/electrical_studies', blank=True, null=True)

    class Meta:
        verbose_name = 'Electrical studies'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.budgeted_hours)


class Consultancies(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateField(blank=False, null=False)
    budgeted_hours = models.ForeignKey(BudgetedHours, on_delete=models.CASCADE, blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    lesson_type = models.IntegerField(choices=LESSON_TYPE, blank=False, null=False)
    action_plan = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='static/static/lessons/consultancies', blank=True, null=True)

    class Meta:
        verbose_name = 'Consultancies'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.budgeted_hours)


SUBCATEGORY = [
    (1, 'Función de protección'),
    (2, 'Simulación'),
    (3, 'Informe'),
    (4, 'Otro')
]

ELEMENT_TYPE = [
    (1, 'Generador fotovoltaico'),
    (2, 'Generador hidráulico'),
    (3, 'Subestación de transmisión'),
    (4, 'Subestación de distribución'),
    (5, 'Generador térmico'),
    (6, 'Generador eólico'),
    (7, 'Transformador'),
    (8, 'Barra'),
    (9, 'Línea'),
    (10, 'Otro')
]

RELAY_BRAND = [
    (1, 'Siemens'),
    (2, 'GE'),
    (3, 'ABB'),
    (4, 'SEL'),
    (5, 'Schneider'),
    (6, 'ZIV'),
    (7, 'Fusible'),
    (8, 'CB'),
    (9, 'General'),
    (10, 'Otro')
]


class ProtectionCoordinationStudies(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateField(blank=False, null=False)
    budgeted_hours = models.ForeignKey(BudgetedHours, on_delete=models.CASCADE, blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    lesson_type = models.IntegerField(choices=LESSON_TYPE, blank=False, null=False)
    action_plan = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    subcategory = models.IntegerField(choices=SUBCATEGORY, blank=True, null=True)
    subcategory_description = models.CharField(max_length=100, blank=True, null=True)
    element_type = models.IntegerField(choices=ELEMENT_TYPE, blank=True, null=True)
    element_type_description = models.CharField(max_length=100, blank=True, null=True)
    protection = models.CharField(max_length=255, blank=True, null=True)
    relay_brand = models.IntegerField(choices=RELAY_BRAND, blank=True, null=True)
    relay_brand_description = models.CharField(max_length=100, blank=True, null=True)
    relay_model = models.CharField(max_length=255, blank=True, null=True)
    file = models.FileField(upload_to='static/static/lessons/protection_coordination_studies', blank=True, null=True)

    class Meta:
        verbose_name = 'Protection coordination studies'
        ordering = ['-created_at']

    def __str__(self):
        return str(self.budgeted_hours)


class Zones(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)

    class Meta:
        verbose_name = 'Zone'
        verbose_name_plural = 'Zones'
        ordering = ['name']

    def __str__(self):
        return str(self.name)


class Operators(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    zone = models.ForeignKey(Zones, on_delete=models.CASCADE, blank=False, null=False)

    class Meta:
        verbose_name = "Operator"
        verbose_name_plural = "Operators"
        ordering = ['name']

    def __str__(self):
        return str(self.name)


class Areas(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    operator = models.ForeignKey(Operators, on_delete=models.CASCADE, blank=False, null=False)

    class Meta:
        verbose_name = "Area"
        verbose_name_plural = "Areas"
        ordering = ['name']

    def __str__(self):
        return str(self.name)

    def zone(self):
        return self.operator.zone


SUBCATEGORY_2 = [
    (1, 'Ajuste de la base de datos'),
    (2, 'Revisión de la información'),
    (3, 'Análisis'),
    (4, 'Informe y anexos')
]


class ConnectionStudies(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateField(blank=False, null=False)
    budgeted_hours = models.ForeignKey(BudgetedHours, on_delete=models.CASCADE, blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    zone = models.ForeignKey(Zones, on_delete=models.CASCADE, blank=False, null=False)
    operator = models.ForeignKey(Operators, on_delete=models.CASCADE, blank=False, null=False)
    area = models.ForeignKey(Areas, on_delete=models.CASCADE, blank=False, null=False)
    lesson_type = models.IntegerField(choices=LESSON_TYPE, blank=False, null=False)
    subcategory = models.IntegerField(choices=SUBCATEGORY_2, blank=True, null=True)
    action_plan = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='static/static/lessons/connection_studies', blank=True, null=True)

    # description = models.TextField( blank=True, null=True)
    # date = models.DateField(blank=False, null=False)
    # code = models.CharField(max_length=255, blank=True, null=False)
    # responsable = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    # created_by = models.ForeignKey(User, related_name='created_by', on_delete=models.CASCADE, null=False)
    # type = models.ForeignKey(LessonType, on_delete=models.CASCADE, null=False)
    # file  = models.FileField(upload_to="static/connection_studies", null=True, blank=True)

    class Meta:
        verbose_name = "Connection studies"
        ordering = ['-created_at']

    def __str__(self):
        return str(self.budgeted_hours)

    def get_filename(self):
        w = self.file.url.split('/')
        if len(w):
            return w[-1]

        return 'Ver archivo'


STUDY_TYPE = [
    (1, 'Estudio de mercado'),
    (2, 'Proyección de precios'),
    (3, 'Estudios energéticos - Estudios de conexión'),
    (4, 'Asesoría')
]


class MarketStudies(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateField(blank=False, null=False)
    budgeted_hours = models.ForeignKey(BudgetedHours, on_delete=models.CASCADE, blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    study_type = models.IntegerField(choices=STUDY_TYPE, blank=True, null=True)
    lesson_type = models.IntegerField(choices=LESSON_TYPE, blank=False, null=False)
    subcategory = models.IntegerField(choices=SUBCATEGORY_2, blank=True, null=True)
    action_plan = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='static/static/lessons/market_studies', blank=True, null=True)

    class Meta:
        verbose_name = "Market studies"
        ordering = ['-created_at']

    def __str__(self):
        return str(self.budgeted_hours)

    def get_filename(self):
        w = self.file.url.split('/')
        if len(w):
            return w[-1]


################################################################################

# class LessonType(models.Model):
#     name = models.CharField(max_length=255, blank=False, null=False)
#     def __str__(self):
#         return str(self.name)

#     class Meta:
#         verbose_name = "Tipo de lección"
#         verbose_name_plural = "Tipo de lecciónes"


# class StudyType(models.Model):
#     name = models.CharField(max_length=255, blank=False, null=False)

#     def __str__(self):
#         return str(self.name)


#     class Meta:
#         ordering = ('-name',)
#         verbose_name = "Tipo de estudio"
#         verbose_name_plural = "Tipo de estudios"

# class InformationType(models.Model):
#     name = models.CharField(max_length=255, blank=False, null=False)
#     study_type = models.ForeignKey(StudyType, on_delete=models.CASCADE, null=False, default=0)
    
#     def __str__(self):
#         return str(self.name)

#     class Meta:
#         ordering = ('name',)
#         verbose_name = "Tipo de información"
#         verbose_name_plural = "Tipo de informaciones"


# class Characteristic(models.Model):
#     name = models.CharField(max_length=255, blank=False, null=False)

lessons/templates/consultancies/change.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Asesorías</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Editar</h4>
                <p class="card-title-desc">Actualice la información</p>

                <form method='POST' enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form|crispy }}

                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-primary float-right">Guardar</button>
                            <a href="{% url 'lessons:consultancies_list' %}" class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

lessons/templates/consultancies/create.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% comment %} {% block head %}
    <link href="{% static 'libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">
{% endblock head %} {% endcomment %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Asesorías</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Crear</h4>
                <p class="card-title-desc">Ingrese la información que desea registrar</p>

                <form method="POST" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form|crispy }}

                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-primary float-right">Guardar</button>
                            <a href="{% url 'lessons:consultancies_list' %}"  class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

{% comment %} {% block scripts %}
    <script src="{% static 'libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>

    <script>
        $(function(){
            $("#id_created_at").datepicker({
                autoclose:!0,
                format: 'dd/mm/yyyy',
                todayHighlight:!0
            }).attr('readonly', 'false')
        })
    </script>
{% endblock scripts %} {% endcomment %}

lessons/templates/consultancies/delete.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Asesorías</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Eliminar</h4>

                <form method='POST'>

                    {% csrf_token %}

                    <p>Realmente desea eliminar este elemento?</p>
                    <p>
                        Proyecto: <b>{{ consultancies }}</b>
                    </p>

                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-danger float-right">Eliminar</button>
                            <a href="{% url 'lessons:consultancies_list' %}" class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

lessons/templates/consultancies/detail.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Asesorías</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-10">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">{{ consultancies.budgeted_hours }}</h4>
            </div>
            <div class="card-body">

                <p>
                    <b>Palabras clave:</b> {{ consultancies.title|default:"" }}<br/>
                    <b>Fecha:</b> {{ consultancies.created_at }}<br/>
                    <b>Cliente:</b> {{ consultancies.client|default:"" }}<br/>
                    <b>Responsable:</b> {{ consultancies.created_by.first_name }} {{ consultancies.created_by.last_name }}<br/>
                    <b>Tipo de lección:</b> {{ consultancies.get_lesson_type_display }}<br/>
                    <b>Descripción:</b> {{ consultancies.description }}<br/>
                    <b>Plan de acción propuesto:</b> {{ consultancies.action_plan }}<br/>
                    {% if consultancies.file %}
                        <b>Archivo:</b> <a href="/{{ consultancies.file }}" target="_blank">Descargar</a><br/>
                    {% endif %}
                </p>

            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'lessons:consultancies_list' %}"  class="btn btn-light">Regresar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

lessons/templates/consultancies/list.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}

{% block head %}
<!-- DataTables -->
<link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

<!-- Responsive datatable examples -->
<link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock head %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Asesorías</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">
                    Lista
                    <a class='float-right btn btn-success' href="{% url 'lessons:consultancies_create' %}">Crear</a>
                </h4>

                <div class="table-responsive">
                    <table id="datatable-buttons" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead>
                            <tr>
                                <th>Palabras clave</th>
                                <th>Creado en</th>
                                <th>Código</th>
                                <th>Cliente</th>
                                <th>Tipo de lección</th>
                                <th>Descripción</th>
                                <th>Plan de acción</th>
                                <th class="text-right">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in consultancies %}
                                <tr>
                                    <td>{{ item.title|default:"" }}</td>
                                    <td><a href="{% url 'lessons:consultancies_detail' item.pk %}">{{ item.created_at }}</a></td>
                                    <td>{{ item.budgeted_hours|default:"" }}</td>
                                    <td>{{ item.client|default:"" }}</td>
                                    <td>{{ item.get_lesson_type_display }}</td>
                                    <td>{{ item.description|default:"" }}</td>
                                    <td>{{ item.action_plan|default:"" }}</td>
                                    <td class="text-right">
                                        <a href="{% url 'lessons:consultancies_change' item.pk  %}" class="btn btn-warning btn-sm">Editar</a>
                                        <a href="{% url 'lessons:consultancies_delete' item.pk  %}" class="btn btn-danger btn-sm">Eliminar</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<!-- JAVASCRIPT -->
<script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'libs/node-waves/waves.min.js' %}"></script>
<script src="{% static 'libs/jquery-sparkline/jquery.sparkline.min.js' %}"></script>

<!-- Required datatable js -->
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>

<!-- Buttons examples -->
<script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/jszip/jszip.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

<!-- Responsive examples -->
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable init js -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

<!-- App js -->
<script src="{% static 'js/app.js' %}"></script>
{% endblock scripts %}