api/urls.py
from django.urls import path
from .views import (
    index,
    download_graphed_data
)


app_name = 'api'


urlpatterns = [
    path('', index, name='api'),
    path('download_graphed_data', download_graphed_data, name='download_graphed_data'),
   
]

dashboard/urls.py
from django.urls import path
from .views import (
    phenomenon,
    metric,
    files_metric,
    downloads,
    index,
    search
)


app_name = 'dashboard'


urlpatterns = [



    path('', index.index, name='home'),


    path('meec/standar', index.standar, name='standar'),
    path('meec/standar/generation', index.generation_api, name='generation'),
    path('search', search.index, name='search'),
    path('search/get-component', search.get_components_by_metric, name='get_components_by_metric'),
  



    path('lang', phenomenon.set_language, name='set_language'),

    path('phenomenons', phenomenon.PhenomenonListView.as_view(), name='phenomenon_list'),
    path('phenomenons/create', phenomenon.PhenomenonCreateView.as_view(), name='phenomenon_create'),
    path('phenomenons/<int:pk>', phenomenon.PhenomenonDetailView.as_view(), name='phenomenon_view'),
    path('phenomenons/<int:pk>/delete', phenomenon.PhenomenonDeleteView.as_view(), name='phenomenon_delete'),

    path('metrics', metric.MetricListView.as_view(), name = 'metrics_list'),
    path('metrics/create', metric.MetricCreateView.as_view(), name = 'metric_create'),
    path('metrics/<int:pk>', metric.MetricDetailView.as_view(), name = 'metric_view'),
    path('metrics/<int:pk>/delete', metric.MetricDeleteView.as_view(), name = 'metric_delete'),

    path('files_metrics', files_metric.UrlsFilesMetricListView.as_view(), name = 'files_metrics_list'),
    path('files_metrics/create', files_metric.UrlsFilesMetricCreateView.as_view(), name = 'files_metrics_create'),
    path('files_metrics/<int:pk>', files_metric.UrlsFilesMetricDetailView.as_view(), name = 'files_metrics_view'),
    path('files_metrics/<int:pk>/delete', files_metric.UrlsFilesMetricDeleteView.as_view(), name = 'files_metrics_delete'),
    path('files_metrics/<int:pk>/process', files_metric.UrlsFilesMetricProcessView.as_view(), name = 'files_metrics_process'),

    path('standard_downloads', downloads.standard_downloads, name = 'standard_downloads')

]

datcore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('users.urls', namespace='users')),
    path('imports/', include('imports.urls', namespace='imports')),
    path('api/', include('api.urls', namespace='api')),
    path('lessons/', include('lessons.urls', namespace='lessons')),
    path('sddp/', include('sddp.urls', namespace='sddp')),
    path('budgeted_hours/', include('budgeted_hours.urls', namespace='budgeted_hours')),
    path('reported_hours/', include('reported_hours.urls', namespace='reported_hours')),
    path('record_business_interactions/', include('record_business_interactions.urls', namespace='record_business_interactions')),
    path('vacations/', include('vacations.urls', namespace = 'vacations')),
    path('configuration_sddp/', include('configuration_sddp.urls', namespace = 'configuration_sddp')),
    path('documents/', include('documents.urls', namespace='documents')),
    path('markers/', include('markers.urls', namespace='markers')),
]
 

documents/urls.py
from django.urls import path
from .views import (
    documents,
    area
)


app_name = 'documents'


urlpatterns = [
    path('documents', documents.DocumentsListView.as_view(), name = 'documents_list'),   
    path('documents/create', documents.DocumentsCreateView.as_view(), name = 'documents_create'),
    path('documents/<int:pk>/detail', documents.DocumentsDetailView.as_view(), name = 'documents_detail'),
    path('documents/<int:pk>/change', documents.DocumentsUpdateView.as_view(), name = 'documents_change'),
    path('documents/<int:pk>/delete', documents.DocumentsDeleteView.as_view(), name = 'documents_delete'),
    
    path('area', area.AreaListView.as_view(), name = 'area_list'),   
    path('area/create', area.AreaCreateView.as_view(), name = 'area_create'),
    path('area/<int:pk>/change', area.AreaUpdateView.as_view(), name = 'area_change'),
    path('area/<int:pk>/delete', area.AreaDeleteView.as_view(), name = 'area_delete'),
]

lessons/urls.py
from django.urls import path
from .views import (
    electrical_studies,
    consultancies,
    protection_coordination_studies,
    connection_studies,
    market_studies,
    reports
)


app_name = 'lessons'


urlpatterns = [
    path('electrical-studies', electrical_studies.ElectricalStudiesListView.as_view(), name='electrical_studies_list'),
    path('electrical-studies/create', electrical_studies.ElectricalStudiesCreateView.as_view(), name='electrical_studies_create'),
    path('electrical-studies/<int:pk>/view', electrical_studies.ElectricalStudiesDetailView.as_view(), name='electrical_studies_detail'),
    path('electrical-studies/<int:pk>/change', electrical_studies.ElectricalStudiesUpdateView.as_view(), name='electrical_studies_change'),
    path('electrical-studies/<int:pk>/delete', electrical_studies.ElectricalStudiesDeleteView.as_view(), name='electrical_studies_delete'),

    path('consultancies', consultancies.ConsultanciesListView.as_view(), name='consultancies_list'),
    path('consultancies/create', consultancies.ConsultanciesCreateView.as_view(), name='consultancies_create'),
    path('consultancies/<int:pk>/view', consultancies.ConsultanciesDetailView.as_view(), name='consultancies_detail'),
    path('consultancies/<int:pk>/change', consultancies.ConsultanciesUpdateView.as_view(), name='consultancies_change'),
    path('consultancies/<int:pk>/delete', consultancies.ConsultanciesDeleteView.as_view(), name='consultancies_delete'),

    path('protection-coordination-studies', protection_coordination_studies.ProtectionCoordinationStudiesListView.as_view(), name='protection_coordination_studies_list'),
    path('protection-coordination-studies/create', protection_coordination_studies.ProtectionCoordinationStudiesCreateView.as_view(), name='protection_coordination_studies_create'),
    path('protection-coordination-studies/<int:pk>/view', protection_coordination_studies.ProtectionCoordinationStudiesDetailView.as_view(), name='protection_coordination_studies_detail'),
    path('protection-coordination-studies/<int:pk>/change', protection_coordination_studies.ProtectionCoordinationStudiesUpdateView.as_view(), name='protection_coordination_studies_change'),
    path('protection-coordination-studies/<int:pk>/delete', protection_coordination_studies.ProtectionCoordinationStudiesDeleteView.as_view(), name='protection_coordination_studies_delete'),

    path('connection-studies', connection_studies.ConnectionStudiesListView.as_view(), name='connection_studies_list'),
    path('connection-studies/create', connection_studies.ConnectionStudiesCreateView.as_view(), name='connection_studies_create'),
    path('connection-studies/<int:pk>/view', connection_studies.ConnectionStudiesDetailView.as_view(), name='connection_studies_detail'),
    path('connection-studies/<int:pk>/change', connection_studies.ConnectionStudiesChangeView.as_view(), name='connection_studies_change'),
    path('connection-studies/<int:pk>/delete', connection_studies.ConnectionStudiesDeleteView.as_view(), name='connection_studies_delete'),

    path('connection-studies/operatos', connection_studies.getOperators, name='operatos'),
    path('connection-studies/areas', connection_studies.getAreas, name='areas'),

    path('market-studies', market_studies.MarketStudiesListView.as_view(), name='market_studies_list'),
    path('market-studies/create', market_studies.MarketStudiesCreateView.as_view(), name='market_studies_create'),
    path('market-studies/<int:pk>/view', market_studies.MarketStudiesDetailView.as_view(), name='market_studies_detail'),
    path('market-studies/<int:pk>/change', market_studies.MarketStudiesChangeView.as_view(), name='market_studies_change'),
    path('market-studies/<int:pk>/delete', market_studies.MarketStudiesDeleteView.as_view(), name='market_studies_delete'),

    path('reports', reports.ReportsTemplateView.as_view(), name='reports_lessons'),

    # path('commercial', commercial.CommercialListView.as_view(), name='commercial_list'),
    # path('commercial/create', commercial.CommercialCreateView.as_view(), name='commercial_create'),
    # path('commercial/<int:pk>/view', commercial.CommercialDetailView.as_view(), name='commercial_detail'),
    # path('commercial/<int:pk>/change', commercial.CommercialChangeView.as_view(), name='commercial_change'),
    # path('commercial/<int:pk>/delete', commercial.CommercialDeleteView.as_view(), name='commercial_delete'),

    # path('related_area', related_areas.RelatedAreaListView.as_view(), name='related_area_list'),
    # path('related_area/create', related_areas.RelatedAreaCreateView.as_view(), name='related_area_create'),
    # path('related_area/<int:pk>/change', related_areas.RelatedAreaChangeView.as_view(), name='related_area_change'),
    # path('related_area/<int:pk>/delete', related_areas.RelatedAreaDeleteView.as_view(), name='related_area_delete'),

    # path('connection-studies/<int:pk>/view', connection_studies.ConnectionStudiesDetailView.as_view(), name='connection_studies_detail'),

    # path('market-studies/<int:pk>/view', market_studies.MarketStudiesDetailView.as_view(), name='market_studies_detail'),

    # path('market-studies/files/<int:pk>', market_studies_files.MarketStudiesFilesChangeView.as_view(), name='market_studies_list_files'),

    # path('market-studies/information-types', market_studies.get_information_types, name='information_types'),
    # path('market-studies/characteristics', market_studies.get_characteristics, name='characteristics'),

]

markers/urls.py
from django.urls import path
from markers.views import (
    team,
    match   
)



app_name = 'markers'

urlpatterns = [
    path('match', match.MatchListView.as_view(), name = 'match_list'),   
    path('match/create', match.MatchCreateView.as_view(), name = 'match_create'),
    path('match/<int:pk>/detail', match.MatchDetailView.as_view(), name = 'match_detail'),
    path('match/<int:pk>/change', match.MatchUpdateView.as_view(), name = 'match_change'),
    path('match/<int:pk>/delete', match.MatchDeleteView.as_view(), name = 'match_delete'),
    
    path('team', team.TeamListView.as_view(), name = 'team_list'),   
    path('team/create', team.TeamCreateView.as_view(), name = 'team_create'),
    path('team/<int:pk>/detail', team.TeamDetailView.as_view(), name = 'team_detail'),
    path('team/<int:pk>/change', team.TeamUpdateView.as_view(), name = 'team_change'),
    path('team/<int:pk>/delete', team.TeamDeleteView.as_view(), name = 'team_delete'),
]

sddp/urls.py
from django import db
from django.urls import path
from .views import (
    projects, dbs, returnrate, weightblocks, operationalbenefits
)


app_name = 'sddp'


urlpatterns = [

    path('operational-benefits', operationalbenefits.TemplateView.as_view(), name='operational_benefits'),
    path('operational-benefits/dbs', operationalbenefits.get_dbs, name='get_dbs'),
    path('operational-benefits/get-operationalbenefits', operationalbenefits.get_operationalbenefits, name='get_operationalbenefits'),
    path('operational-benefits/download-operationalbenefits', operationalbenefits.download_operationalbenefits, name='download_operationalbenefits'),

    path('projects', projects.ProjectsListView.as_view(), name='projects_list'),
    path('projects/create', projects.ProjectCreateView.as_view(), name='projects_create'),
    path('projects/<int:pk>/delete', projects.ProjectDeleteView.as_view(), name='projects_delete'),

    path('dbs', dbs.DbsListView.as_view(), name='dbs_list'),
    path('dbs/create', dbs.DbsCreateView.as_view(), name='dbs_create'),
    path('dbs/<int:pk>/delete', dbs.DbsDeleteView.as_view(), name='dbs_delete'),

    path('return-rate', returnrate.ReturnRateListView.as_view(), name='returnrate_list'),
    path('return-rate/create', returnrate.ReturnRateCreateView.as_view(), name='returnrate_create'),
    path('return-rate/<int:pk>/delete', returnrate.ReturnRateDeleteView.as_view(), name='returnrate_delete'),
    path('return-rate/<int:pk>/change', returnrate.ReturnRateChangeView.as_view(), name='returnrate_change'),
  
    path('weight-blocks', weightblocks.WeightBlocksListView.as_view(), name='weightblocks_list'),
    path('weight-blocks/create', weightblocks.WeightBlocksCreateView.as_view(), name='weightblocks_create'),
    path('weight-blocks/<int:pk>/delete', weightblocks.WeightBlocksDeleteView.as_view(), name='weightblocks_delete'),
    path('weight-blocks/<int:pk>/change', weightblocks.WeightBlocksChangeView.as_view(), name='weightblocks_change'),
 
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views/downloads.py
import io

import pandas as pd
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from dashboard.helpers.charts import (calculateMarginalPlant, 
                                      check_and_defaults_marginal_plant, dailyContributionsByMonth, 
                                      generation, 
                                      netEffectiveCapacity,
                                      check_and_defaults_net_effective_capacity,
                                      maximumNationalOfferPrice,
                                      yearlyBagPrices,
                                      monthlyBagPrices,
                                      usefulDailyVolumePercentage
                                      )

from django.views.decorators.csrf import csrf_exempt
from django.conf import settings

@csrf_exempt
def standard_downloads(request):
    """

        Process downloads of submits buttons for download data from standard graphics 

        References:
            https://stackoverflow.com/questions/20448911/get-id-of-one-of-multiple-buttons-in-html-form-in-django
    """

    if 'net_effective_capacity' in request.GET.keys():

        date = check_and_defaults_net_effective_capacity(request)
        data = list(zip(*netEffectiveCapacity(date)[:3]))

        df = pd.DataFrame(data, columns=['Tecnología', 'Capacidad[MW]', 'Participacion[%]'])

        return df2xlsx_response(df, 'Capacidad efectiva neta.xlsx')        

    elif 'generation' in request.GET.keys():
        
        data, _, names_traces = generation()
        data = list(zip(*data))

        name_columns = ['Fecha'] + names_traces + ['Participacion termica']        
        df = pd.DataFrame(data, columns=name_columns)

        return df2xlsx_response(df, 'Generacion.xlsx')

    elif 'monthly_bag_price' in request.GET.keys():

        monthly_bag_prices_chart, girl_phenomenons, boy_phenomenons = monthlyBagPrices()

        df = pd.DataFrame({'Fecha':monthly_bag_prices_chart[0], 'Precio de bolsa':monthly_bag_prices_chart[1]}).set_index('Fecha')
        df['Niño'] = ''
        df['Niña'] = '' 
        for d, v  in zip(*girl_phenomenons):
            print(d, v)
            df.loc[d, 'Niña'] = v

        for d, v  in zip(*boy_phenomenons):
            print(d, v)
            df.loc[d, 'Niño'] = v  

        df.reset_index(inplace=True)
        
        return df2xlsx_response(df, 'Precio de bolsa mensual.xlsx')

    elif 'yearly_bag_price' in request.GET.keys():

        data = yearlyBagPrices()
        df = pd.DataFrame(data)
        df = df.T
        df.columns  = ['Fecha', 'Valor']
        #df = pd.DataFrame(data, columns=['Fecha', 'Valor'])
        return df2xlsx_response(df, 'Precio de bolsa anual.xlsx')

    elif 'energy_demand' in request.GET.keys():
       
        data = maximumNationalOfferPrice()
        df = pd.DataFrame(data)
        df = df.T
        df.columns  = ['Fecha', 'Valor']
        return df2xlsx_response(df, 'Demanda de energia.xlsx')

    elif 'marginal_plant' in request.GET.keys():

        start, end, amount_plants, margin_error = check_and_defaults_marginal_plant(request)
        data = list(zip(*calculateMarginalPlant(start, end, amount_plants, margin_error)))

        df = pd.DataFrame(data, columns=['Planta', 'Veces que margina'])

        return df2xlsx_response(df, 'Planta que margina.xlsx')        

    elif 'useful_percentage_chart' in request.GET.keys():
        data = usefulDailyVolumePercentage()
        
        df = pd.DataFrame(data).T
        df.columns = ['Fecha', 'Valor']

        return df2xlsx_response(df, 'Embalse Agregado del Sistema.xlsx')        

    elif 'daily_contributions_by_month' in request.GET.keys():
        data = dailyContributionsByMonth()
        
        df = pd.DataFrame(data)

        return df2xlsx_response(df[::-1], 'Historico Aportes Diario.xlsx')

    else:
        raise NotImplementedError('Standard download for this file not implemented')


def df2xlsx_response(df, name_file):
    """
        References:
            https://stackoverflow.com/questions/28058563/write-to-stringio-object-using-pandas-excelwriter
            https://stackoverflow.com/questions/48488697/python-django-offering-a-zip-file-for-download-from-io-bytesio-buffer  
    """


    base = settings.PROJECT_PATH

    path_file = f'{base}/cache/{name_file}'
   
    # Write dataframe in a buffer
    writer = pd.ExcelWriter(path_file, engine='xlsxwriter')

    df.to_excel(writer, index=False)
    writer.save() 

    # Define response object with xlsx file
    response = HttpResponse(io.open(path_file, mode="rb").read(), content_type='application/xlsx')
    response['Content-Disposition'] = f'attachment; filename={name_file}'

    return response

dashboard/templates/dashboard/home.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}




{% block content %}
    <!-- start page title -->
    <div class="row">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h1>Datcore</h1>

            </div>
        </div>
    </div>
    <!-- end page title -->
  
    
<div class="row">
    {% if perms.imports.view_metric %}
        <div class="col-xl-3 col-md-3">
            <div class="card directory-card">
                <div>
                    <div class="directory-content text-center p-4">
                        <p>
                            <a href='{% url 'dashboard:standar'%}' ><img class='img-fluid' src='{% static 'images/illustrations/report.svg' %}'  style='top:0; height:111px'></a>
                        </p>
                        <h4 class="">MEC</h4>
                        {% comment %} <a class='btn btn-info btn-xl btn-block' href='{% url 'dashboard:standar'%}'>Ingresar</a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if perms.sddp.view_project or perms.sddp.view_dbs %}
        <div class="col-xl-3 col-md-3">
            <div class="card directory-card">
                <div>
                    <div class="directory-content text-center p-4">
                        <p>
                            <a href='{% url 'sddp:projects_list'%}' ><img class='img-fluid' src='{% static 'images/illustrations/sddp.svg' %}'  style='top:0; height:111px'></a>
                        </p>
                        <h4 class="">SDDP</h4>
                        {% comment %} <a class='btn btn-info btn-xl  btn-block' href='{% url 'sddp:projects_list'%}'>Ingresar</a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if perms.lessons.view_connectionstudies  %}
    <div class="col-xl-3 col-md-3">
        <div class="card directory-card">
            <div>
                <div class="directory-content text-center p-4">
                    <p>
                        <a href='{% url 'lessons:connection_studies_list' %}' ><img class='img-fluid' src='{% static 'images/illustrations/projects.svg' %}'  style='top:0; height:111px'></a>
                    </p>
                    <h4 class="">Lecciones aprendidas</h4>
                    {% comment %} <a class='btn btn-info btn-xl btn-block' href='{% url 'lessons:connection_studies_list' %}'>Ingresar</a> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}


    {% if perms.budgeted_hours.view_budgetedhours %}
        <div class="col-xl-3 col-md-3">
            <div class="card directory-card">
                <div>
                    <div class="directory-content text-center p-4">
                        <p>
                            <a href='{% url 'budgeted_hours:budgeted_hours_list' %}' ><img class='img-fluid' src='{% static 'images/illustrations/calendar.svg' %}'  style='top:0; height:111px'></a>
                        </p>
                        <h4 class="">Horas presupuestadas</h4>
                        {% comment %} <a class='btn btn-info btn-xl btn-block' href='{% url 'budgeted_hours:budgeted_hours_list' %}'>Ingresar</a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if perms.record_business_interactions.view_visitrecord %}

        <div class="col-xl-3 col-md-3">
            <div class="card directory-card">
                <div>
                    <div class="directory-content text-center p-4">
                        <p>
                            <a href='{% url 'record_business_interactions:visit_record_list' %}' ><img class='img-fluid' src='{% static 'images/illustrations/record_business_interactions.svg' %}'  style='top:0; height:111px'></a>
                        </p>
                        <h4 class="">Interacciones comerciales</h4>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
    
    <div class="col-xl-3 col-md-3">
        <div class="card directory-card">
            <div>
                <div class="directory-content text-center p-4">
                    <p>
                        <a href='{% url 'reported_hours:reported_hours_list' %}' ><img class='img-fluid' src="{% static 'images/illustrations/time.svg' %}"  style="top:0; height:111px"></a>
                    </p>
                    <h4 class="">Reporte de tiempo</h4>
                    {% comment %} <a class='btn btn-info btn-xl btn-block' href='{% url 'lessons:connection_studies_list' %}'>Ingresar</a> {% endcomment %}
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-3">
        <div class="card directory-card">
            <div>
                <div class="directory-content text-center p-4">
                    <p>
                        <a href="{% url 'vacations:requests_list' %}"><img class='img-fluid' src="{% static 'images/illustrations/vacations.svg' %}" style='top:0; height:111px'></a>
                    </p>
                    <h4 class="">Vacaciones</h4>
                </div>
            </div>
        </div>
    </div>


    <div class="col-xl-3 col-md-3">
        <div class="card directory-card">
            <div>
                <div class="directory-content text-center p-4">
                    <p>
                        <a target="_blank" href="https://360.phc.com.co/api/datcore?email={{ user.email }}"><img class='img-fluid' src="{% static 'images/illustrations/evaluation.svg' %}" style='top:0; height:111px'></a>
                    </p>
                    <h4 class="">Evaluación de desempeño</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-3">
        <div class="card directory-card">
            <div>
                <div class="directory-content text-center p-4">
                    <p>
                        <a href="{% url 'documents:documents_list'%}"><img class='img-fluid' src="{% static 'images/illustrations/documents.svg' %}" style='top:0; height:111px'></a>
                    </p>
                    <h4 class="">Plantillas PHC</h4>
                </div>
            </div>
        </div>
    </div>


    <div class="col-xl-3 col-md-3">
        <div class="card directory-card">
            <div>
                <div class="directory-content text-center p-4">
                    <p>
                        <a href="{% url 'markers:team_list'%}"><img class='img-fluid' src="{% static 'images/illustrations/documents.svg' %}" style='top:0; height:111px'></a>
                    </p>
                    <h4 class="">Marcadores</h4>
                </div>
            </div>
        </div>
    </div>
    <!-- end col -->

    

</div>



{% endblock content %}