api/urls.py
from django.urls import path
from .views import (
    index,
    download_graphed_data
)


app_name = 'api'


urlpatterns = [
    path('', index, name='api'),
    path('download_graphed_data', download_graphed_data, name='download_graphed_data'),
   
]

datcore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('users.urls', namespace='users')),
    path('imports/', include('imports.urls', namespace='imports')),
    path('api/', include('api.urls', namespace='api')),
    path('lessons/', include('lessons.urls', namespace='lessons')),
    path('sddp/', include('sddp.urls', namespace='sddp')),
    path('budgeted_hours/', include('budgeted_hours.urls', namespace='budgeted_hours')),
    path('reported_hours/', include('reported_hours.urls', namespace='reported_hours')),
    path('record_business_interactions/', include('record_business_interactions.urls', namespace='record_business_interactions')),
    path('vacations/', include('vacations.urls', namespace = 'vacations')),
    path('configuration_sddp/', include('configuration_sddp.urls', namespace = 'configuration_sddp')),
    path('documents/', include('documents.urls', namespace='documents')),
    path('markers/', include('markers.urls', namespace='markers')),
]
 

documents/urls.py
from django.urls import path
from .views import (
    documents,
    area
)


app_name = 'documents'


urlpatterns = [
    path('documents', documents.DocumentsListView.as_view(), name = 'documents_list'),   
    path('documents/create', documents.DocumentsCreateView.as_view(), name = 'documents_create'),
    path('documents/<int:pk>/detail', documents.DocumentsDetailView.as_view(), name = 'documents_detail'),
    path('documents/<int:pk>/change', documents.DocumentsUpdateView.as_view(), name = 'documents_change'),
    path('documents/<int:pk>/delete', documents.DocumentsDeleteView.as_view(), name = 'documents_delete'),
    
    path('area', area.AreaListView.as_view(), name = 'area_list'),   
    path('area/create', area.AreaCreateView.as_view(), name = 'area_create'),
    path('area/<int:pk>/change', area.AreaUpdateView.as_view(), name = 'area_change'),
    path('area/<int:pk>/delete', area.AreaDeleteView.as_view(), name = 'area_delete'),
]

documents/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Area(models.Model):
    area = models.CharField(max_length=50, blank=False, null=False)
    
    class Meta:
        verbose_name = 'Area'
        ordering=['area']
        
        
    def __str__(self):
        return str(self.area) 


class Templates(models.Model):
    area = models.ForeignKey(Area, on_delete=models.CASCADE, blank=False, null=False)
    title = models.CharField(max_length=100, blank=False, null=False)
    description = models.TextField(max_length=200,blank=False, null=False)
    file = models.FileField(upload_to = 'static/static/documents', blank=False, null=False)  
    created_at = models.DateField(blank=False, null=False) 
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)

    class Meta:
        verbose_name = 'Templates'
        ordering=['title']

    def __str__(self):
        return str(self.title) 

documents/forms/area_form.py
from django import forms
from documents.models import Area


class AreaForm(forms.ModelForm):
    
    class Meta:
        model = Area
        
        fields = (
            'area',
        )
        
        labels = {
            'area': 'Área',
        }

documents/forms/templates_form.py
from django import forms
from documents.models import Templates

class TemplatesForm(forms.ModelForm):
    
    class Meta:
        model = Templates 
        
        fields = (
            'created_at',
            'created_by',
            'area',
            'title',
            'description',            
            'file',            
        )
        
        labels = {
            'created_at': 'Fecha',
            'created_by': 'Responsable',
            'area': 'Área',
            'title': 'Título',
            'description': 'Descripción',
            'file': 'Archivo',
        }
        

documents/views/area.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from documents.models import Area
from documents.forms.area_form import AreaForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages


class AreaListView(PermissionRequiredMixin, ListView):
    
    model = Area
    template_name: str = 'area/list.html'
    context_object_name = 'area'
    permission_required = 'documents.view_area'
    
class AreaCreateView(PermissionRequiredMixin, CreateView):
    
    model = Area
    form_class = AreaForm
    template_name = 'area/create.html'
    success_url = reverse_lazy('documents:area_list')
    permission_required = 'documents.add_area'
    
    
    def form_valid ( self , form ) :
        messages.success ( self.request , ' Registro creado con éxito ' )
        return super ( ) . form_valid ( form )

class AreaUpdateView(PermissionRequiredMixin, UpdateView):
    
    model = Area 
    form_class = AreaForm
    template_name = 'area/change.html'
    success_url = reverse_lazy('documents:area_list')
    permission_required = 'documents.change_area'

    def form_valid ( self , form ) :
        messages.success ( self.request , ' Registro actualizado con éxito ' )
        return super ( ) . form_valid ( form )
    
    
class AreaDeleteView(PermissionRequiredMixin, DeleteView):
    
    model = Area
    template_name = 'area/delete.html'
    success_url = reverse_lazy('documents:area_list')
    context_object_name = 'area'
    permission_required = 'documents.delete_area'


    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Registro eliminado con éxito')
        return super().delete(*args, **kwargs)
    

            
              

documents/views/documents.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from documents.models import Templates
from documents.forms.templates_form import TemplatesForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages

# Create your views here.
class DocumentsListView(PermissionRequiredMixin, ListView):
    
    model = Templates
    template_name: str = 'documents/list.html'
    context_object_name = 'documents'
    permission_required = 'documents.view_templates'
    
class DocumentsCreateView(PermissionRequiredMixin, CreateView):
    
    model = Templates
    form_class = TemplatesForm
    template_name = 'documents/create.html'
    success_url = reverse_lazy('documents:documents_list')
    permission_required = 'documents.add_templates'
    
    
    def form_valid ( self , form ) :
        messages.success ( self.request , ' Registro creado con éxito ' )
        return super ( ) . form_valid ( form )

class DocumentsUpdateView(PermissionRequiredMixin,UpdateView):
    
    model = Templates 
    form_class = TemplatesForm
    template_name = 'documents/change.html'
    success_url = reverse_lazy('documents:documents_list')
    permission_required = 'documents.change_templates'

    def form_valid ( self , form ) :
        messages.success ( self.request , ' Registro actualizado con éxito ' )
        return super ( ) . form_valid ( form )
    
    
class DocumentsDeleteView(PermissionRequiredMixin, DeleteView):
    
    model = Templates
    template_name = 'documents/delete.html'
    success_url = reverse_lazy('documents:documents_list')
    context_object_name = 'documents'
    permission_required = 'documents.delete_templates'


    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Registro eliminado con éxito')
        return super().delete(*args, **kwargs)
    

class DocumentsDetailView(PermissionRequiredMixin, DetailView):
    
    model = Templates
    template_name = 'documents/detail.html'
    context_object_name = 'documents'
    permission_required = 'documents.view_templates'
    

documents/templates/documents/change.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link href="{% static 'libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Plantillas PHC</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Editar</h4>
                <p class="card-title-desc">Actualice la información</p>

                <form method='POST' enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form|crispy }}

                    <div class="form-group mb-0">
                        <div>
                            
                            <button type="submit" class="btn btn-primary float-right">Guardar</button>
                            <a href="{% url 'documents:documents_list' %}" class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>

    <script>
        $(function(){
            $("#id_created_at").datepicker({
                autoclose:!0,
                format: 'dd/mm/yyyy',
                todayHighlight:!0
            }).attr('readonly', 'false')
        })
        
    </script>
{% endblock scripts %}

documents/templates/documents/create.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link href="{% static 'libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Plantillas PHC</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Crear</h4>
                <p class="card-title-desc">Ingrese la información que desea registrar</p>

                <form method="POST" enctype="multipart/form-data">

                    

                    {% csrf_token %}
                    {{ form|crispy }}

                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-primary float-right">Guardar</button>
                            <a href="{% url 'documents:documents_list' %}"  class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>

    <script>
        $(function(){
            $("#id_created_at").datepicker({
                autoclose:!0,
                format: 'dd/mm/yyyy',
                todayHighlight:!0
            }).attr('readonly', 'false')
        })
        
    </script>
{% endblock scripts %}

documents/templates/documents/delete.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Plantillas PHC</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Eliminar</h4>

                <form method='POST'>

                    {% csrf_token %}

                    <p>Realmente desea eliminar este elemento?</p>
                    <p>
                        Plantilla: <b>{{ documents }}</b>
                    </p>

                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-danger float-right">Eliminar</button>
                            <a href="{% url 'documents:documents_list' %}" class="btn btn-light">Regresar</a>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

documents/templates/documents/detail.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
 
{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Plantillas PHC </h4>
        </div>
    </div>
</div>
 
<div class="row">
    <div class="col-10">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">{{ documents.title }}</h4>
            </div>
            <div class="card-body">
 
                <p>
                    <b>Fecha:</b> {{ documents.created_at }}<br/>
                    <b>Responsable:</b> {{ documents.created_by }}<br/>
                    <b>Area:</b> {{ documents.area }}<br/>
                    <b>Descripción:</b> {{ documents.description }}<br/>
                    
                    {% if documents.file %}
                        <b>Archivo:</b> <a href="/{{ documents.file }}" target="_blank">Descargar</a><br/>
                    {% endif %}
                </p>
 
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'documents:documents_list' %}"  class="btn btn-light">Regresar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end col -->
</div>
{% endblock content %}

documents/templates/documents/list.html
{% extends "layouts/app.html" %}
{% load i18n %}
{% load static %}

{% block head %}
<!-- DataTables -->
<link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

<!-- Responsive datatable examples -->
<link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock head %}

{% block content %}
<!-- start page title -->
<div class="row">
    <div class="col-sm-6">
        <div class="page-title-box">
            <h4>Plantillas PHC</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">
                    Lista
                    {% if perms.documents.add_templates %}
                    <a class='float-right btn btn-success' href="{% url 'documents:documents_create' %}">Crear</a>
                    {% endif %}
                </h4>

                <div class="table-responsive">
                    <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead>
                            <tr>
                                <th>Título</th>
                                <th>Área</th>
                                <th>Descripción</th>
                                <th>Fecha </th>
                                <th> Responsable </th> 
                                <th class="text-right">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in documents %}
                                <tr>
                                    <td><a href="{% url 'documents:documents_detail' item.id %}">{{ item.title}}</a></td>
                                    <td>{{ item.area }}</td>
                                    <td>{{ item.description}}</td>
                                    <td>{{ item.created_at}} </td>
                                    <td>{{ item.created_by}} </td>
                                    <td class="text-right">
                                        {% if perms.documents.change_templates %}
                                        <a href="{% url 'documents:documents_change' item.id %}" class="btn btn-warning btn-sm">Editar</a>
                                        {% endif %}
                                        {% if perms.documents.delete_templates %}
                                        <a href="{% url 'documents:documents_delete' item.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<!-- JAVASCRIPT -->
<script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'libs/node-waves/waves.min.js' %}"></script>
<script src="{% static 'libs/jquery-sparkline/jquery.sparkline.min.js' %}"></script>

<!-- Required datatable js -->
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>

<!-- Buttons examples -->
<script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/jszip/jszip.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

<!-- Responsive examples -->
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable init js -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

<!-- App js -->
<script src="{% static 'js/app.js' %}"></script>
{% endblock scripts %}